### ISSUE TITLE
Implement and train unet with our masks from watershed being our label

### ISSUE THREAD

**Issue by TerenceTYAranowitz** [UC-Irvine-CS175/final-project-e-mcheese-2#10]
#### Description
We will implement UNET with the image masks being our watershed masks. May need to add changes as we go.

#### Files (may changes but I think this is what we will need to create/change)
src/models/unet_model/config.py
src/models/unet_model/model.py
src/models/unet_model/train.py
src/models/unet_model/predict.py
src/dataset/bps_dataset.py

#### Tasks
- [ ] Find dependencies we need for UNET and add that to our environment setup
- [ ] Learn
- [ ] Implement Unet with our watershed masks being the desired output

**Comment by nadia-eecs** [comment]
@TerenceTYAranowitz , can you visualize the output of the watershed by calling performe_tsne from the new hw assignment and plotting the 2d scatter to see if the low resolution masks separate better than the raw data? 

### What that would look like?
Take a sample of images you'd like to plot, let's say 1000 (to follow the hw):
- 1-d ify (2d->1d images) watershed output images
-  append the 1-d images to a list
-  input them into perform_tsne to get their 2-component representation
-  see if the dots separate well or are at least apart from each other

### What does that tell you?
- It gives a litmus test on potentially confusing images that you could isolate out.

### Why am I advising you to do this?
- I think doing an unsupervised segmentation-->downsampling and then upsampling the images to see how it segments by doing some plots (like you did for watershed) and comparing it to the output of watershed will be an interesting case study for computer vision vs. traditional image processing techniques in the context of cellular microscopy. 

- It will also give you an idea on whether using watershed as your mask is too aggressive or if it works for your use case without having to invest too much training time.

- You will directly be using the current hw code for your study.

That will help intuitively understand whether setting the watershed output as a mask is a good idea or if unsupervised segmentation approaches are more useful since we don't have labels.
